/*
Cube Osmium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PositionsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PositionsGet200Response{}

// PositionsGet200Response struct for PositionsGet200Response
type PositionsGet200Response struct {
	Result []PositionsGet200ResponseResultInner `json:"result"`
}

type _PositionsGet200Response PositionsGet200Response

// NewPositionsGet200Response instantiates a new PositionsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPositionsGet200Response(result []PositionsGet200ResponseResultInner) *PositionsGet200Response {
	this := PositionsGet200Response{}
	this.Result = result
	return &this
}

// NewPositionsGet200ResponseWithDefaults instantiates a new PositionsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPositionsGet200ResponseWithDefaults() *PositionsGet200Response {
	this := PositionsGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *PositionsGet200Response) GetResult() []PositionsGet200ResponseResultInner {
	if o == nil {
		var ret []PositionsGet200ResponseResultInner
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *PositionsGet200Response) GetResultOk() ([]PositionsGet200ResponseResultInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *PositionsGet200Response) SetResult(v []PositionsGet200ResponseResultInner) {
	o.Result = v
}

func (o PositionsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PositionsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *PositionsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPositionsGet200Response := _PositionsGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPositionsGet200Response)

	if err != nil {
		return err
	}

	*o = PositionsGet200Response(varPositionsGet200Response)

	return err
}

type NullablePositionsGet200Response struct {
	value *PositionsGet200Response
	isSet bool
}

func (v NullablePositionsGet200Response) Get() *PositionsGet200Response {
	return v.value
}

func (v *NullablePositionsGet200Response) Set(val *PositionsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePositionsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePositionsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePositionsGet200Response(val *PositionsGet200Response) *NullablePositionsGet200Response {
	return &NullablePositionsGet200Response{value: val, isSet: true}
}

func (v NullablePositionsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePositionsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


