/*
Cube Osmium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderPatch200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderPatch200Response{}

// OrderPatch200Response struct for OrderPatch200Response
type OrderPatch200Response struct {
	Result OrderPatch200ResponseResult `json:"result"`
}

type _OrderPatch200Response OrderPatch200Response

// NewOrderPatch200Response instantiates a new OrderPatch200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderPatch200Response(result OrderPatch200ResponseResult) *OrderPatch200Response {
	this := OrderPatch200Response{}
	this.Result = result
	return &this
}

// NewOrderPatch200ResponseWithDefaults instantiates a new OrderPatch200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderPatch200ResponseWithDefaults() *OrderPatch200Response {
	this := OrderPatch200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *OrderPatch200Response) GetResult() OrderPatch200ResponseResult {
	if o == nil {
		var ret OrderPatch200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *OrderPatch200Response) GetResultOk() (*OrderPatch200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *OrderPatch200Response) SetResult(v OrderPatch200ResponseResult) {
	o.Result = v
}

func (o OrderPatch200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderPatch200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *OrderPatch200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderPatch200Response := _OrderPatch200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderPatch200Response)

	if err != nil {
		return err
	}

	*o = OrderPatch200Response(varOrderPatch200Response)

	return err
}

type NullableOrderPatch200Response struct {
	value *OrderPatch200Response
	isSet bool
}

func (v NullableOrderPatch200Response) Get() *OrderPatch200Response {
	return v.value
}

func (v *NullableOrderPatch200Response) Set(val *OrderPatch200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderPatch200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderPatch200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderPatch200Response(val *OrderPatch200Response) *NullableOrderPatch200Response {
	return &NullableOrderPatch200Response{value: val, isSet: true}
}

func (v NullableOrderPatch200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderPatch200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


