/*
Cube Osmium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderPost200Response{}

// OrderPost200Response struct for OrderPost200Response
type OrderPost200Response struct {
	Result OrderPost200ResponseResult `json:"result"`
}

type _OrderPost200Response OrderPost200Response

// NewOrderPost200Response instantiates a new OrderPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderPost200Response(result OrderPost200ResponseResult) *OrderPost200Response {
	this := OrderPost200Response{}
	this.Result = result
	return &this
}

// NewOrderPost200ResponseWithDefaults instantiates a new OrderPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderPost200ResponseWithDefaults() *OrderPost200Response {
	this := OrderPost200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *OrderPost200Response) GetResult() OrderPost200ResponseResult {
	if o == nil {
		var ret OrderPost200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *OrderPost200Response) GetResultOk() (*OrderPost200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *OrderPost200Response) SetResult(v OrderPost200ResponseResult) {
	o.Result = v
}

func (o OrderPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *OrderPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderPost200Response := _OrderPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderPost200Response)

	if err != nil {
		return err
	}

	*o = OrderPost200Response(varOrderPost200Response)

	return err
}

type NullableOrderPost200Response struct {
	value *OrderPost200Response
	isSet bool
}

func (v NullableOrderPost200Response) Get() *OrderPost200Response {
	return v.value
}

func (v *NullableOrderPost200Response) Set(val *OrderPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderPost200Response(val *OrderPost200Response) *NullableOrderPost200Response {
	return &NullableOrderPost200Response{value: val, isSet: true}
}

func (v NullableOrderPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


