/*
Cube Osmium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrdersDelete200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrdersDelete200Response{}

// OrdersDelete200Response struct for OrdersDelete200Response
type OrdersDelete200Response struct {
	Result OrdersDelete200ResponseResult `json:"result"`
}

type _OrdersDelete200Response OrdersDelete200Response

// NewOrdersDelete200Response instantiates a new OrdersDelete200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersDelete200Response(result OrdersDelete200ResponseResult) *OrdersDelete200Response {
	this := OrdersDelete200Response{}
	this.Result = result
	return &this
}

// NewOrdersDelete200ResponseWithDefaults instantiates a new OrdersDelete200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersDelete200ResponseWithDefaults() *OrdersDelete200Response {
	this := OrdersDelete200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *OrdersDelete200Response) GetResult() OrdersDelete200ResponseResult {
	if o == nil {
		var ret OrdersDelete200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *OrdersDelete200Response) GetResultOk() (*OrdersDelete200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *OrdersDelete200Response) SetResult(v OrdersDelete200ResponseResult) {
	o.Result = v
}

func (o OrdersDelete200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrdersDelete200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *OrdersDelete200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrdersDelete200Response := _OrdersDelete200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrdersDelete200Response)

	if err != nil {
		return err
	}

	*o = OrdersDelete200Response(varOrdersDelete200Response)

	return err
}

type NullableOrdersDelete200Response struct {
	value *OrdersDelete200Response
	isSet bool
}

func (v NullableOrdersDelete200Response) Get() *OrdersDelete200Response {
	return v.value
}

func (v *NullableOrdersDelete200Response) Set(val *OrdersDelete200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersDelete200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersDelete200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersDelete200Response(val *OrdersDelete200Response) *NullableOrdersDelete200Response {
	return &NullableOrdersDelete200Response{value: val, isSet: true}
}

func (v NullableOrdersDelete200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersDelete200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


