/*
Cube Mendelev HTTP API

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService BookMarketIdRecentTradesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var marketId string

		resp, httpRes, err := apiClient.DefaultAPI.BookMarketIdRecentTradesGet(context.Background(), marketId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService BookMarketIdSnapshotGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var marketId string

		resp, httpRes, err := apiClient.DefaultAPI.BookMarketIdSnapshotGet(context.Background(), marketId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ParsedBookMarketSymbolRecentTradesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var marketSymbol string

		resp, httpRes, err := apiClient.DefaultAPI.ParsedBookMarketSymbolRecentTradesGet(context.Background(), marketSymbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ParsedBookMarketSymbolSnapshotGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var marketSymbol string

		resp, httpRes, err := apiClient.DefaultAPI.ParsedBookMarketSymbolSnapshotGet(context.Background(), marketSymbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ParsedTickersGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.ParsedTickersGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService TickersSnapshotGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.TickersSnapshotGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
