/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersAddressGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersAddressGet200Response{}

// UsersAddressGet200Response struct for UsersAddressGet200Response
type UsersAddressGet200Response struct {
	Result UsersAddressGet200ResponseResult `json:"result"`
}

type _UsersAddressGet200Response UsersAddressGet200Response

// NewUsersAddressGet200Response instantiates a new UsersAddressGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersAddressGet200Response(result UsersAddressGet200ResponseResult) *UsersAddressGet200Response {
	this := UsersAddressGet200Response{}
	this.Result = result
	return &this
}

// NewUsersAddressGet200ResponseWithDefaults instantiates a new UsersAddressGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersAddressGet200ResponseWithDefaults() *UsersAddressGet200Response {
	this := UsersAddressGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersAddressGet200Response) GetResult() UsersAddressGet200ResponseResult {
	if o == nil {
		var ret UsersAddressGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersAddressGet200Response) GetResultOk() (*UsersAddressGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersAddressGet200Response) SetResult(v UsersAddressGet200ResponseResult) {
	o.Result = v
}

func (o UsersAddressGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersAddressGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersAddressGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersAddressGet200Response := _UsersAddressGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersAddressGet200Response)

	if err != nil {
		return err
	}

	*o = UsersAddressGet200Response(varUsersAddressGet200Response)

	return err
}

type NullableUsersAddressGet200Response struct {
	value *UsersAddressGet200Response
	isSet bool
}

func (v NullableUsersAddressGet200Response) Get() *UsersAddressGet200Response {
	return v.value
}

func (v *NullableUsersAddressGet200Response) Set(val *UsersAddressGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersAddressGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersAddressGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersAddressGet200Response(val *UsersAddressGet200Response) *NullableUsersAddressGet200Response {
	return &NullableUsersAddressGet200Response{value: val, isSet: true}
}

func (v NullableUsersAddressGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersAddressGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


