/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersSubaccountSubaccountIdOrdersGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersSubaccountSubaccountIdOrdersGet200Response{}

// UsersSubaccountSubaccountIdOrdersGet200Response struct for UsersSubaccountSubaccountIdOrdersGet200Response
type UsersSubaccountSubaccountIdOrdersGet200Response struct {
	Result UsersSubaccountSubaccountIdOrdersGet200ResponseResult `json:"result"`
}

type _UsersSubaccountSubaccountIdOrdersGet200Response UsersSubaccountSubaccountIdOrdersGet200Response

// NewUsersSubaccountSubaccountIdOrdersGet200Response instantiates a new UsersSubaccountSubaccountIdOrdersGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersSubaccountSubaccountIdOrdersGet200Response(result UsersSubaccountSubaccountIdOrdersGet200ResponseResult) *UsersSubaccountSubaccountIdOrdersGet200Response {
	this := UsersSubaccountSubaccountIdOrdersGet200Response{}
	this.Result = result
	return &this
}

// NewUsersSubaccountSubaccountIdOrdersGet200ResponseWithDefaults instantiates a new UsersSubaccountSubaccountIdOrdersGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersSubaccountSubaccountIdOrdersGet200ResponseWithDefaults() *UsersSubaccountSubaccountIdOrdersGet200Response {
	this := UsersSubaccountSubaccountIdOrdersGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersSubaccountSubaccountIdOrdersGet200Response) GetResult() UsersSubaccountSubaccountIdOrdersGet200ResponseResult {
	if o == nil {
		var ret UsersSubaccountSubaccountIdOrdersGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersSubaccountSubaccountIdOrdersGet200Response) GetResultOk() (*UsersSubaccountSubaccountIdOrdersGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersSubaccountSubaccountIdOrdersGet200Response) SetResult(v UsersSubaccountSubaccountIdOrdersGet200ResponseResult) {
	o.Result = v
}

func (o UsersSubaccountSubaccountIdOrdersGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersSubaccountSubaccountIdOrdersGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersSubaccountSubaccountIdOrdersGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersSubaccountSubaccountIdOrdersGet200Response := _UsersSubaccountSubaccountIdOrdersGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersSubaccountSubaccountIdOrdersGet200Response)

	if err != nil {
		return err
	}

	*o = UsersSubaccountSubaccountIdOrdersGet200Response(varUsersSubaccountSubaccountIdOrdersGet200Response)

	return err
}

type NullableUsersSubaccountSubaccountIdOrdersGet200Response struct {
	value *UsersSubaccountSubaccountIdOrdersGet200Response
	isSet bool
}

func (v NullableUsersSubaccountSubaccountIdOrdersGet200Response) Get() *UsersSubaccountSubaccountIdOrdersGet200Response {
	return v.value
}

func (v *NullableUsersSubaccountSubaccountIdOrdersGet200Response) Set(val *UsersSubaccountSubaccountIdOrdersGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersSubaccountSubaccountIdOrdersGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersSubaccountSubaccountIdOrdersGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersSubaccountSubaccountIdOrdersGet200Response(val *UsersSubaccountSubaccountIdOrdersGet200Response) *NullableUsersSubaccountSubaccountIdOrdersGet200Response {
	return &NullableUsersSubaccountSubaccountIdOrdersGet200Response{value: val, isSet: true}
}

func (v NullableUsersSubaccountSubaccountIdOrdersGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersSubaccountSubaccountIdOrdersGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


