/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HistoryKlinesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HistoryKlinesGet200Response{}

// HistoryKlinesGet200Response struct for HistoryKlinesGet200Response
type HistoryKlinesGet200Response struct {
	Result [][]string `json:"result"`
}

type _HistoryKlinesGet200Response HistoryKlinesGet200Response

// NewHistoryKlinesGet200Response instantiates a new HistoryKlinesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHistoryKlinesGet200Response(result [][]string) *HistoryKlinesGet200Response {
	this := HistoryKlinesGet200Response{}
	this.Result = result
	return &this
}

// NewHistoryKlinesGet200ResponseWithDefaults instantiates a new HistoryKlinesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHistoryKlinesGet200ResponseWithDefaults() *HistoryKlinesGet200Response {
	this := HistoryKlinesGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *HistoryKlinesGet200Response) GetResult() [][]string {
	if o == nil {
		var ret [][]string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *HistoryKlinesGet200Response) GetResultOk() ([][]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *HistoryKlinesGet200Response) SetResult(v [][]string) {
	o.Result = v
}

func (o HistoryKlinesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HistoryKlinesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *HistoryKlinesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHistoryKlinesGet200Response := _HistoryKlinesGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHistoryKlinesGet200Response)

	if err != nil {
		return err
	}

	*o = HistoryKlinesGet200Response(varHistoryKlinesGet200Response)

	return err
}

type NullableHistoryKlinesGet200Response struct {
	value *HistoryKlinesGet200Response
	isSet bool
}

func (v NullableHistoryKlinesGet200Response) Get() *HistoryKlinesGet200Response {
	return v.value
}

func (v *NullableHistoryKlinesGet200Response) Set(val *HistoryKlinesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHistoryKlinesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHistoryKlinesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHistoryKlinesGet200Response(val *HistoryKlinesGet200Response) *NullableHistoryKlinesGet200Response {
	return &NullableHistoryKlinesGet200Response{value: val, isSet: true}
}

func (v NullableHistoryKlinesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHistoryKlinesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


