/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersCheckGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersCheckGet200Response{}

// UsersCheckGet200Response struct for UsersCheckGet200Response
type UsersCheckGet200Response struct {
	Result UsersCheckGet200ResponseResult `json:"result"`
}

type _UsersCheckGet200Response UsersCheckGet200Response

// NewUsersCheckGet200Response instantiates a new UsersCheckGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersCheckGet200Response(result UsersCheckGet200ResponseResult) *UsersCheckGet200Response {
	this := UsersCheckGet200Response{}
	this.Result = result
	return &this
}

// NewUsersCheckGet200ResponseWithDefaults instantiates a new UsersCheckGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersCheckGet200ResponseWithDefaults() *UsersCheckGet200Response {
	this := UsersCheckGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersCheckGet200Response) GetResult() UsersCheckGet200ResponseResult {
	if o == nil {
		var ret UsersCheckGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersCheckGet200Response) GetResultOk() (*UsersCheckGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersCheckGet200Response) SetResult(v UsersCheckGet200ResponseResult) {
	o.Result = v
}

func (o UsersCheckGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersCheckGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersCheckGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersCheckGet200Response := _UsersCheckGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersCheckGet200Response)

	if err != nil {
		return err
	}

	*o = UsersCheckGet200Response(varUsersCheckGet200Response)

	return err
}

type NullableUsersCheckGet200Response struct {
	value *UsersCheckGet200Response
	isSet bool
}

func (v NullableUsersCheckGet200Response) Get() *UsersCheckGet200Response {
	return v.value
}

func (v *NullableUsersCheckGet200Response) Set(val *UsersCheckGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersCheckGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersCheckGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersCheckGet200Response(val *UsersCheckGet200Response) *NullableUsersCheckGet200Response {
	return &NullableUsersCheckGet200Response{value: val, isSet: true}
}

func (v NullableUsersCheckGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersCheckGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


