/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MarketsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketsGet200Response{}

// MarketsGet200Response struct for MarketsGet200Response
type MarketsGet200Response struct {
	Result MarketsGet200ResponseResult `json:"result"`
}

type _MarketsGet200Response MarketsGet200Response

// NewMarketsGet200Response instantiates a new MarketsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketsGet200Response(result MarketsGet200ResponseResult) *MarketsGet200Response {
	this := MarketsGet200Response{}
	this.Result = result
	return &this
}

// NewMarketsGet200ResponseWithDefaults instantiates a new MarketsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketsGet200ResponseWithDefaults() *MarketsGet200Response {
	this := MarketsGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *MarketsGet200Response) GetResult() MarketsGet200ResponseResult {
	if o == nil {
		var ret MarketsGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *MarketsGet200Response) GetResultOk() (*MarketsGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *MarketsGet200Response) SetResult(v MarketsGet200ResponseResult) {
	o.Result = v
}

func (o MarketsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *MarketsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMarketsGet200Response := _MarketsGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMarketsGet200Response)

	if err != nil {
		return err
	}

	*o = MarketsGet200Response(varMarketsGet200Response)

	return err
}

type NullableMarketsGet200Response struct {
	value *MarketsGet200Response
	isSet bool
}

func (v NullableMarketsGet200Response) Get() *MarketsGet200Response {
	return v.value
}

func (v *NullableMarketsGet200Response) Set(val *MarketsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketsGet200Response(val *MarketsGet200Response) *NullableMarketsGet200Response {
	return &NullableMarketsGet200Response{value: val, isSet: true}
}

func (v NullableMarketsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


