/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersSubaccountSubaccountIdPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersSubaccountSubaccountIdPatchRequest{}

// UsersSubaccountSubaccountIdPatchRequest struct for UsersSubaccountSubaccountIdPatchRequest
type UsersSubaccountSubaccountIdPatchRequest struct {
	Name string `json:"name"`
}

type _UsersSubaccountSubaccountIdPatchRequest UsersSubaccountSubaccountIdPatchRequest

// NewUsersSubaccountSubaccountIdPatchRequest instantiates a new UsersSubaccountSubaccountIdPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersSubaccountSubaccountIdPatchRequest(name string) *UsersSubaccountSubaccountIdPatchRequest {
	this := UsersSubaccountSubaccountIdPatchRequest{}
	this.Name = name
	return &this
}

// NewUsersSubaccountSubaccountIdPatchRequestWithDefaults instantiates a new UsersSubaccountSubaccountIdPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersSubaccountSubaccountIdPatchRequestWithDefaults() *UsersSubaccountSubaccountIdPatchRequest {
	this := UsersSubaccountSubaccountIdPatchRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UsersSubaccountSubaccountIdPatchRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UsersSubaccountSubaccountIdPatchRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UsersSubaccountSubaccountIdPatchRequest) SetName(v string) {
	o.Name = v
}

func (o UsersSubaccountSubaccountIdPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersSubaccountSubaccountIdPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UsersSubaccountSubaccountIdPatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersSubaccountSubaccountIdPatchRequest := _UsersSubaccountSubaccountIdPatchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersSubaccountSubaccountIdPatchRequest)

	if err != nil {
		return err
	}

	*o = UsersSubaccountSubaccountIdPatchRequest(varUsersSubaccountSubaccountIdPatchRequest)

	return err
}

type NullableUsersSubaccountSubaccountIdPatchRequest struct {
	value *UsersSubaccountSubaccountIdPatchRequest
	isSet bool
}

func (v NullableUsersSubaccountSubaccountIdPatchRequest) Get() *UsersSubaccountSubaccountIdPatchRequest {
	return v.value
}

func (v *NullableUsersSubaccountSubaccountIdPatchRequest) Set(val *UsersSubaccountSubaccountIdPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersSubaccountSubaccountIdPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersSubaccountSubaccountIdPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersSubaccountSubaccountIdPatchRequest(val *UsersSubaccountSubaccountIdPatchRequest) *NullableUsersSubaccountSubaccountIdPatchRequest {
	return &NullableUsersSubaccountSubaccountIdPatchRequest{value: val, isSet: true}
}

func (v NullableUsersSubaccountSubaccountIdPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersSubaccountSubaccountIdPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


