/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersSubaccountSubaccountIdDepositsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersSubaccountSubaccountIdDepositsGet200Response{}

// UsersSubaccountSubaccountIdDepositsGet200Response struct for UsersSubaccountSubaccountIdDepositsGet200Response
type UsersSubaccountSubaccountIdDepositsGet200Response struct {
	Result map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultDepositsValue `json:"result"`
}

type _UsersSubaccountSubaccountIdDepositsGet200Response UsersSubaccountSubaccountIdDepositsGet200Response

// NewUsersSubaccountSubaccountIdDepositsGet200Response instantiates a new UsersSubaccountSubaccountIdDepositsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersSubaccountSubaccountIdDepositsGet200Response(result map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultDepositsValue) *UsersSubaccountSubaccountIdDepositsGet200Response {
	this := UsersSubaccountSubaccountIdDepositsGet200Response{}
	this.Result = result
	return &this
}

// NewUsersSubaccountSubaccountIdDepositsGet200ResponseWithDefaults instantiates a new UsersSubaccountSubaccountIdDepositsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersSubaccountSubaccountIdDepositsGet200ResponseWithDefaults() *UsersSubaccountSubaccountIdDepositsGet200Response {
	this := UsersSubaccountSubaccountIdDepositsGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersSubaccountSubaccountIdDepositsGet200Response) GetResult() map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultDepositsValue {
	if o == nil {
		var ret map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultDepositsValue
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersSubaccountSubaccountIdDepositsGet200Response) GetResultOk() (*map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultDepositsValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersSubaccountSubaccountIdDepositsGet200Response) SetResult(v map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultDepositsValue) {
	o.Result = v
}

func (o UsersSubaccountSubaccountIdDepositsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersSubaccountSubaccountIdDepositsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersSubaccountSubaccountIdDepositsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersSubaccountSubaccountIdDepositsGet200Response := _UsersSubaccountSubaccountIdDepositsGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersSubaccountSubaccountIdDepositsGet200Response)

	if err != nil {
		return err
	}

	*o = UsersSubaccountSubaccountIdDepositsGet200Response(varUsersSubaccountSubaccountIdDepositsGet200Response)

	return err
}

type NullableUsersSubaccountSubaccountIdDepositsGet200Response struct {
	value *UsersSubaccountSubaccountIdDepositsGet200Response
	isSet bool
}

func (v NullableUsersSubaccountSubaccountIdDepositsGet200Response) Get() *UsersSubaccountSubaccountIdDepositsGet200Response {
	return v.value
}

func (v *NullableUsersSubaccountSubaccountIdDepositsGet200Response) Set(val *UsersSubaccountSubaccountIdDepositsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersSubaccountSubaccountIdDepositsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersSubaccountSubaccountIdDepositsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersSubaccountSubaccountIdDepositsGet200Response(val *UsersSubaccountSubaccountIdDepositsGet200Response) *NullableUsersSubaccountSubaccountIdDepositsGet200Response {
	return &NullableUsersSubaccountSubaccountIdDepositsGet200Response{value: val, isSet: true}
}

func (v NullableUsersSubaccountSubaccountIdDepositsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersSubaccountSubaccountIdDepositsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


