/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersSubaccountSubaccountIdTransfersGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersSubaccountSubaccountIdTransfersGet200Response{}

// UsersSubaccountSubaccountIdTransfersGet200Response struct for UsersSubaccountSubaccountIdTransfersGet200Response
type UsersSubaccountSubaccountIdTransfersGet200Response struct {
	Result UsersSubaccountSubaccountIdTransfersGet200ResponseResult `json:"result"`
}

type _UsersSubaccountSubaccountIdTransfersGet200Response UsersSubaccountSubaccountIdTransfersGet200Response

// NewUsersSubaccountSubaccountIdTransfersGet200Response instantiates a new UsersSubaccountSubaccountIdTransfersGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersSubaccountSubaccountIdTransfersGet200Response(result UsersSubaccountSubaccountIdTransfersGet200ResponseResult) *UsersSubaccountSubaccountIdTransfersGet200Response {
	this := UsersSubaccountSubaccountIdTransfersGet200Response{}
	this.Result = result
	return &this
}

// NewUsersSubaccountSubaccountIdTransfersGet200ResponseWithDefaults instantiates a new UsersSubaccountSubaccountIdTransfersGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersSubaccountSubaccountIdTransfersGet200ResponseWithDefaults() *UsersSubaccountSubaccountIdTransfersGet200Response {
	this := UsersSubaccountSubaccountIdTransfersGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersSubaccountSubaccountIdTransfersGet200Response) GetResult() UsersSubaccountSubaccountIdTransfersGet200ResponseResult {
	if o == nil {
		var ret UsersSubaccountSubaccountIdTransfersGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersSubaccountSubaccountIdTransfersGet200Response) GetResultOk() (*UsersSubaccountSubaccountIdTransfersGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersSubaccountSubaccountIdTransfersGet200Response) SetResult(v UsersSubaccountSubaccountIdTransfersGet200ResponseResult) {
	o.Result = v
}

func (o UsersSubaccountSubaccountIdTransfersGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersSubaccountSubaccountIdTransfersGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersSubaccountSubaccountIdTransfersGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersSubaccountSubaccountIdTransfersGet200Response := _UsersSubaccountSubaccountIdTransfersGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersSubaccountSubaccountIdTransfersGet200Response)

	if err != nil {
		return err
	}

	*o = UsersSubaccountSubaccountIdTransfersGet200Response(varUsersSubaccountSubaccountIdTransfersGet200Response)

	return err
}

type NullableUsersSubaccountSubaccountIdTransfersGet200Response struct {
	value *UsersSubaccountSubaccountIdTransfersGet200Response
	isSet bool
}

func (v NullableUsersSubaccountSubaccountIdTransfersGet200Response) Get() *UsersSubaccountSubaccountIdTransfersGet200Response {
	return v.value
}

func (v *NullableUsersSubaccountSubaccountIdTransfersGet200Response) Set(val *UsersSubaccountSubaccountIdTransfersGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersSubaccountSubaccountIdTransfersGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersSubaccountSubaccountIdTransfersGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersSubaccountSubaccountIdTransfersGet200Response(val *UsersSubaccountSubaccountIdTransfersGet200Response) *NullableUsersSubaccountSubaccountIdTransfersGet200Response {
	return &NullableUsersSubaccountSubaccountIdTransfersGet200Response{value: val, isSet: true}
}

func (v NullableUsersSubaccountSubaccountIdTransfersGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersSubaccountSubaccountIdTransfersGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


