/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersSubaccountsPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersSubaccountsPost200Response{}

// UsersSubaccountsPost200Response struct for UsersSubaccountsPost200Response
type UsersSubaccountsPost200Response struct {
	Result UsersSubaccountsPost200ResponseResult `json:"result"`
}

type _UsersSubaccountsPost200Response UsersSubaccountsPost200Response

// NewUsersSubaccountsPost200Response instantiates a new UsersSubaccountsPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersSubaccountsPost200Response(result UsersSubaccountsPost200ResponseResult) *UsersSubaccountsPost200Response {
	this := UsersSubaccountsPost200Response{}
	this.Result = result
	return &this
}

// NewUsersSubaccountsPost200ResponseWithDefaults instantiates a new UsersSubaccountsPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersSubaccountsPost200ResponseWithDefaults() *UsersSubaccountsPost200Response {
	this := UsersSubaccountsPost200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersSubaccountsPost200Response) GetResult() UsersSubaccountsPost200ResponseResult {
	if o == nil {
		var ret UsersSubaccountsPost200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersSubaccountsPost200Response) GetResultOk() (*UsersSubaccountsPost200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersSubaccountsPost200Response) SetResult(v UsersSubaccountsPost200ResponseResult) {
	o.Result = v
}

func (o UsersSubaccountsPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersSubaccountsPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersSubaccountsPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersSubaccountsPost200Response := _UsersSubaccountsPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersSubaccountsPost200Response)

	if err != nil {
		return err
	}

	*o = UsersSubaccountsPost200Response(varUsersSubaccountsPost200Response)

	return err
}

type NullableUsersSubaccountsPost200Response struct {
	value *UsersSubaccountsPost200Response
	isSet bool
}

func (v NullableUsersSubaccountsPost200Response) Get() *UsersSubaccountsPost200Response {
	return v.value
}

func (v *NullableUsersSubaccountsPost200Response) Set(val *UsersSubaccountsPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersSubaccountsPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersSubaccountsPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersSubaccountsPost200Response(val *UsersSubaccountsPost200Response) *NullableUsersSubaccountsPost200Response {
	return &NullableUsersSubaccountsPost200Response{value: val, isSet: true}
}

func (v NullableUsersSubaccountsPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersSubaccountsPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


