/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersFeeEstimateMarketIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersFeeEstimateMarketIdGet200Response{}

// UsersFeeEstimateMarketIdGet200Response struct for UsersFeeEstimateMarketIdGet200Response
type UsersFeeEstimateMarketIdGet200Response struct {
	Result UsersFeeEstimateMarketIdGet200ResponseResult `json:"result"`
}

type _UsersFeeEstimateMarketIdGet200Response UsersFeeEstimateMarketIdGet200Response

// NewUsersFeeEstimateMarketIdGet200Response instantiates a new UsersFeeEstimateMarketIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersFeeEstimateMarketIdGet200Response(result UsersFeeEstimateMarketIdGet200ResponseResult) *UsersFeeEstimateMarketIdGet200Response {
	this := UsersFeeEstimateMarketIdGet200Response{}
	this.Result = result
	return &this
}

// NewUsersFeeEstimateMarketIdGet200ResponseWithDefaults instantiates a new UsersFeeEstimateMarketIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersFeeEstimateMarketIdGet200ResponseWithDefaults() *UsersFeeEstimateMarketIdGet200Response {
	this := UsersFeeEstimateMarketIdGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersFeeEstimateMarketIdGet200Response) GetResult() UsersFeeEstimateMarketIdGet200ResponseResult {
	if o == nil {
		var ret UsersFeeEstimateMarketIdGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersFeeEstimateMarketIdGet200Response) GetResultOk() (*UsersFeeEstimateMarketIdGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersFeeEstimateMarketIdGet200Response) SetResult(v UsersFeeEstimateMarketIdGet200ResponseResult) {
	o.Result = v
}

func (o UsersFeeEstimateMarketIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersFeeEstimateMarketIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersFeeEstimateMarketIdGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersFeeEstimateMarketIdGet200Response := _UsersFeeEstimateMarketIdGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersFeeEstimateMarketIdGet200Response)

	if err != nil {
		return err
	}

	*o = UsersFeeEstimateMarketIdGet200Response(varUsersFeeEstimateMarketIdGet200Response)

	return err
}

type NullableUsersFeeEstimateMarketIdGet200Response struct {
	value *UsersFeeEstimateMarketIdGet200Response
	isSet bool
}

func (v NullableUsersFeeEstimateMarketIdGet200Response) Get() *UsersFeeEstimateMarketIdGet200Response {
	return v.value
}

func (v *NullableUsersFeeEstimateMarketIdGet200Response) Set(val *UsersFeeEstimateMarketIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersFeeEstimateMarketIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersFeeEstimateMarketIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersFeeEstimateMarketIdGet200Response(val *UsersFeeEstimateMarketIdGet200Response) *NullableUsersFeeEstimateMarketIdGet200Response {
	return &NullableUsersFeeEstimateMarketIdGet200Response{value: val, isSet: true}
}

func (v NullableUsersFeeEstimateMarketIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersFeeEstimateMarketIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


