/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersSubaccountSubaccountIdWithdrawalsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersSubaccountSubaccountIdWithdrawalsGet200Response{}

// UsersSubaccountSubaccountIdWithdrawalsGet200Response struct for UsersSubaccountSubaccountIdWithdrawalsGet200Response
type UsersSubaccountSubaccountIdWithdrawalsGet200Response struct {
	Result map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue `json:"result"`
}

type _UsersSubaccountSubaccountIdWithdrawalsGet200Response UsersSubaccountSubaccountIdWithdrawalsGet200Response

// NewUsersSubaccountSubaccountIdWithdrawalsGet200Response instantiates a new UsersSubaccountSubaccountIdWithdrawalsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersSubaccountSubaccountIdWithdrawalsGet200Response(result map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue) *UsersSubaccountSubaccountIdWithdrawalsGet200Response {
	this := UsersSubaccountSubaccountIdWithdrawalsGet200Response{}
	this.Result = result
	return &this
}

// NewUsersSubaccountSubaccountIdWithdrawalsGet200ResponseWithDefaults instantiates a new UsersSubaccountSubaccountIdWithdrawalsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersSubaccountSubaccountIdWithdrawalsGet200ResponseWithDefaults() *UsersSubaccountSubaccountIdWithdrawalsGet200Response {
	this := UsersSubaccountSubaccountIdWithdrawalsGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersSubaccountSubaccountIdWithdrawalsGet200Response) GetResult() map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue {
	if o == nil {
		var ret map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersSubaccountSubaccountIdWithdrawalsGet200Response) GetResultOk() (*map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersSubaccountSubaccountIdWithdrawalsGet200Response) SetResult(v map[string]UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue) {
	o.Result = v
}

func (o UsersSubaccountSubaccountIdWithdrawalsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersSubaccountSubaccountIdWithdrawalsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersSubaccountSubaccountIdWithdrawalsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersSubaccountSubaccountIdWithdrawalsGet200Response := _UsersSubaccountSubaccountIdWithdrawalsGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersSubaccountSubaccountIdWithdrawalsGet200Response)

	if err != nil {
		return err
	}

	*o = UsersSubaccountSubaccountIdWithdrawalsGet200Response(varUsersSubaccountSubaccountIdWithdrawalsGet200Response)

	return err
}

type NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response struct {
	value *UsersSubaccountSubaccountIdWithdrawalsGet200Response
	isSet bool
}

func (v NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response) Get() *UsersSubaccountSubaccountIdWithdrawalsGet200Response {
	return v.value
}

func (v *NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response) Set(val *UsersSubaccountSubaccountIdWithdrawalsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersSubaccountSubaccountIdWithdrawalsGet200Response(val *UsersSubaccountSubaccountIdWithdrawalsGet200Response) *NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response {
	return &NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response{value: val, isSet: true}
}

func (v NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersSubaccountSubaccountIdWithdrawalsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


