/*
Cube Iridium HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersInfoGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersInfoGet200Response{}

// UsersInfoGet200Response struct for UsersInfoGet200Response
type UsersInfoGet200Response struct {
	Result UsersInfoGet200ResponseResult `json:"result"`
}

type _UsersInfoGet200Response UsersInfoGet200Response

// NewUsersInfoGet200Response instantiates a new UsersInfoGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersInfoGet200Response(result UsersInfoGet200ResponseResult) *UsersInfoGet200Response {
	this := UsersInfoGet200Response{}
	this.Result = result
	return &this
}

// NewUsersInfoGet200ResponseWithDefaults instantiates a new UsersInfoGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersInfoGet200ResponseWithDefaults() *UsersInfoGet200Response {
	this := UsersInfoGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *UsersInfoGet200Response) GetResult() UsersInfoGet200ResponseResult {
	if o == nil {
		var ret UsersInfoGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UsersInfoGet200Response) GetResultOk() (*UsersInfoGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UsersInfoGet200Response) SetResult(v UsersInfoGet200ResponseResult) {
	o.Result = v
}

func (o UsersInfoGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersInfoGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *UsersInfoGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersInfoGet200Response := _UsersInfoGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersInfoGet200Response)

	if err != nil {
		return err
	}

	*o = UsersInfoGet200Response(varUsersInfoGet200Response)

	return err
}

type NullableUsersInfoGet200Response struct {
	value *UsersInfoGet200Response
	isSet bool
}

func (v NullableUsersInfoGet200Response) Get() *UsersInfoGet200Response {
	return v.value
}

func (v *NullableUsersInfoGet200Response) Set(val *UsersInfoGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersInfoGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersInfoGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersInfoGet200Response(val *UsersInfoGet200Response) *NullableUsersInfoGet200Response {
	return &NullableUsersInfoGet200Response{value: val, isSet: true}
}

func (v NullableUsersInfoGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersInfoGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


