/**
 * Cube Mendelev HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A resting order.
*/
export class BookMarketIdSnapshotGet200ResponseResultAnyOf1OrdersInner {
    'price': number;
    'quantity': number;
    /**
    * [Exchange order ID](./websocket-trade-api.md#exchange-order-id)
    */
    'exchangeOrderId': number;
    'side': number;
    /**
    * Order priority for execution. Valid within a price level and side. That is, orders must first be sorted by side and price (in descending order for bids and ascending for asks), and then the OrderPriority within the level. A lower value is a higher priority.
    */
    'priority': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "exchangeOrderId",
            "baseName": "exchangeOrderId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return BookMarketIdSnapshotGet200ResponseResultAnyOf1OrdersInner.attributeTypeMap;
    }

    public constructor() {
    }
}

