/**
 * Cube Mendelev HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Each price level is the aggregate total quantity of orders placed at that price.
*/
export class BookMarketIdSnapshotGet200ResponseResultAnyOfLevelsInner {
    'price': number;
    'quantity': number;
    'side': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return BookMarketIdSnapshotGet200ResponseResultAnyOfLevelsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

