/**
 * Cube Mendelev HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BookMarketIdRecentTradesGet200ResponseResultTradesInner {
    /**
    * The ID assigned to this trade. All trades that occur from the same event will be assigned the same ID, and are considered to be an atomic batch.
    */
    'tradeId': number;
    /**
    * The price that this trade occurred at.
    */
    'price': number;
    /**
    * The side of the aggressing order.
    */
    'aggressingSide': number;
    /**
    * The [Exchange order ID](./websocket-trade-api.md#exchange-order-id) of the resting order.
    */
    'restingExchangeOrderId': number;
    'fillQuantity': number;
    /**
    * The [transact time](./websocket-trade-api.md#transact-time) assigned by the matching engine for this trade. All trades that occur from the same event will be assigned the same transact time.
    */
    'transactTime': number;
    /**
    * The [Exchange order ID](./websocket-trade-api.md#exchange-order-id) of the aggressing order.
    */
    'aggressingExchangeOrderId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tradeId",
            "baseName": "tradeId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "aggressingSide",
            "baseName": "aggressingSide",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "restingExchangeOrderId",
            "baseName": "restingExchangeOrderId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "fillQuantity",
            "baseName": "fillQuantity",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "transactTime",
            "baseName": "transactTime",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "aggressingExchangeOrderId",
            "baseName": "aggressingExchangeOrderId",
            "type": "number",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return BookMarketIdRecentTradesGet200ResponseResultTradesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

