/**
 * Cube Mendelev HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInner {
    /**
    * The trade ID.
    */
    'id': number;
    /**
    * The price of the trade.
    */
    'p': number;
    /**
    * The quantity of the trade.
    */
    'q': number;
    /**
    * The side of the aggressing order.
    */
    'side': ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInnerSideEnum;
    /**
    * The millisecond timestamp of the trade.
    */
    'ts': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "p",
            "baseName": "p",
            "type": "number",
            "format": "double"
        },
        {
            "name": "q",
            "baseName": "q",
            "type": "number",
            "format": "double"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInnerSideEnum",
            "format": ""
        },
        {
            "name": "ts",
            "baseName": "ts",
            "type": "number",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInnerSideEnum {
    Bid = 'Bid',
    Ask = 'Ask'
}

