/**
 * Cube Mendelev HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInner } from '../models/ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInner';
import { HttpFile } from '../http/http';

export class ParsedBookMarketSymbolRecentTradesGet200ResponseResult {
    'tickerId': string;
    'trades': Array<ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tickerId",
            "baseName": "ticker_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "trades",
            "baseName": "trades",
            "type": "Array<ParsedBookMarketSymbolRecentTradesGet200ResponseResultTradesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ParsedBookMarketSymbolRecentTradesGet200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}

