/**
 * Cube Mendelev HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A market-by-price order book.  Each level contains the price and the total quantity at that price. There may be multiple orders at the same price.
*/
export class ParsedBookMarketSymbolSnapshotGet200ResponseResult {
    'tickerId': string;
    'timestamp': number;
    /**
    * A list of (price, quantity) pairs, sorted by price in descending order.
    */
    'bids': Array<Array<string>>;
    /**
    * A list of (price, quantity) pairs, sorted by price in ascending order.
    */
    'asks': Array<Array<string>>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tickerId",
            "baseName": "ticker_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "bids",
            "baseName": "bids",
            "type": "Array<Array<string>>",
            "format": ""
        },
        {
            "name": "asks",
            "baseName": "asks",
            "type": "Array<Array<string>>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ParsedBookMarketSymbolSnapshotGet200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}

