/**
 * Cube Mendelev HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TickersSnapshotGet200ResponseResultSummariesInner } from '../models/TickersSnapshotGet200ResponseResultSummariesInner';
import { TickersSnapshotGet200ResponseResultTopsInner } from '../models/TickersSnapshotGet200ResponseResultTopsInner';
import { HttpFile } from '../http/http';

export class TickersSnapshotGet200ResponseResult {
    'tops': Array<TickersSnapshotGet200ResponseResultTopsInner>;
    'summaries': Array<TickersSnapshotGet200ResponseResultSummariesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tops",
            "baseName": "tops",
            "type": "Array<TickersSnapshotGet200ResponseResultTopsInner>",
            "format": ""
        },
        {
            "name": "summaries",
            "baseName": "summaries",
            "type": "Array<TickersSnapshotGet200ResponseResultSummariesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TickersSnapshotGet200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}

