/**
 * Cube Mendelev HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Rolling 24h stats.
*/
export class TickersSnapshotGet200ResponseResultSummariesInner {
    'marketId': number;
    /**
    * 24h open price
    */
    'open'?: number | null;
    /**
    * Latest price
    */
    'close'?: number | null;
    /**
    * 24h low price
    */
    'low'?: number | null;
    /**
    * 24h high price
    */
    'high'?: number | null;
    /**
    * Low 64-bits of the base quantity traded
    */
    'baseVolumeLo': number;
    /**
    * High 64-bits of the base quantity traded
    */
    'baseVolumeHi': number;
    /**
    * Low 64-bits of the quote quantity traded
    */
    'quoteVolumeLo': number;
    /**
    * High 64-bits of the quote quantity traded
    */
    'quoteVolumeHi': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "open",
            "baseName": "open",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "close",
            "baseName": "close",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "low",
            "baseName": "low",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "high",
            "baseName": "high",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "baseVolumeLo",
            "baseName": "baseVolumeLo",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "baseVolumeHi",
            "baseName": "baseVolumeHi",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "quoteVolumeLo",
            "baseName": "quoteVolumeLo",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "quoteVolumeHi",
            "baseName": "quoteVolumeHi",
            "type": "number",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return TickersSnapshotGet200ResponseResultSummariesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

