/*
Cube Mendelev HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParsedBookMarketSymbolSnapshotGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParsedBookMarketSymbolSnapshotGet200Response{}

// ParsedBookMarketSymbolSnapshotGet200Response struct for ParsedBookMarketSymbolSnapshotGet200Response
type ParsedBookMarketSymbolSnapshotGet200Response struct {
	Result ParsedBookMarketSymbolSnapshotGet200ResponseResult `json:"result"`
}

type _ParsedBookMarketSymbolSnapshotGet200Response ParsedBookMarketSymbolSnapshotGet200Response

// NewParsedBookMarketSymbolSnapshotGet200Response instantiates a new ParsedBookMarketSymbolSnapshotGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParsedBookMarketSymbolSnapshotGet200Response(result ParsedBookMarketSymbolSnapshotGet200ResponseResult) *ParsedBookMarketSymbolSnapshotGet200Response {
	this := ParsedBookMarketSymbolSnapshotGet200Response{}
	this.Result = result
	return &this
}

// NewParsedBookMarketSymbolSnapshotGet200ResponseWithDefaults instantiates a new ParsedBookMarketSymbolSnapshotGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParsedBookMarketSymbolSnapshotGet200ResponseWithDefaults() *ParsedBookMarketSymbolSnapshotGet200Response {
	this := ParsedBookMarketSymbolSnapshotGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *ParsedBookMarketSymbolSnapshotGet200Response) GetResult() ParsedBookMarketSymbolSnapshotGet200ResponseResult {
	if o == nil {
		var ret ParsedBookMarketSymbolSnapshotGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ParsedBookMarketSymbolSnapshotGet200Response) GetResultOk() (*ParsedBookMarketSymbolSnapshotGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *ParsedBookMarketSymbolSnapshotGet200Response) SetResult(v ParsedBookMarketSymbolSnapshotGet200ResponseResult) {
	o.Result = v
}

func (o ParsedBookMarketSymbolSnapshotGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParsedBookMarketSymbolSnapshotGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *ParsedBookMarketSymbolSnapshotGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParsedBookMarketSymbolSnapshotGet200Response := _ParsedBookMarketSymbolSnapshotGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParsedBookMarketSymbolSnapshotGet200Response)

	if err != nil {
		return err
	}

	*o = ParsedBookMarketSymbolSnapshotGet200Response(varParsedBookMarketSymbolSnapshotGet200Response)

	return err
}

type NullableParsedBookMarketSymbolSnapshotGet200Response struct {
	value *ParsedBookMarketSymbolSnapshotGet200Response
	isSet bool
}

func (v NullableParsedBookMarketSymbolSnapshotGet200Response) Get() *ParsedBookMarketSymbolSnapshotGet200Response {
	return v.value
}

func (v *NullableParsedBookMarketSymbolSnapshotGet200Response) Set(val *ParsedBookMarketSymbolSnapshotGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableParsedBookMarketSymbolSnapshotGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableParsedBookMarketSymbolSnapshotGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParsedBookMarketSymbolSnapshotGet200Response(val *ParsedBookMarketSymbolSnapshotGet200Response) *NullableParsedBookMarketSymbolSnapshotGet200Response {
	return &NullableParsedBookMarketSymbolSnapshotGet200Response{value: val, isSet: true}
}

func (v NullableParsedBookMarketSymbolSnapshotGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParsedBookMarketSymbolSnapshotGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


