/*
Cube Mendelev HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: support@cube.exchange
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParsedBookMarketSymbolRecentTradesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParsedBookMarketSymbolRecentTradesGet200Response{}

// ParsedBookMarketSymbolRecentTradesGet200Response struct for ParsedBookMarketSymbolRecentTradesGet200Response
type ParsedBookMarketSymbolRecentTradesGet200Response struct {
	Result ParsedBookMarketSymbolRecentTradesGet200ResponseResult `json:"result"`
}

type _ParsedBookMarketSymbolRecentTradesGet200Response ParsedBookMarketSymbolRecentTradesGet200Response

// NewParsedBookMarketSymbolRecentTradesGet200Response instantiates a new ParsedBookMarketSymbolRecentTradesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParsedBookMarketSymbolRecentTradesGet200Response(result ParsedBookMarketSymbolRecentTradesGet200ResponseResult) *ParsedBookMarketSymbolRecentTradesGet200Response {
	this := ParsedBookMarketSymbolRecentTradesGet200Response{}
	this.Result = result
	return &this
}

// NewParsedBookMarketSymbolRecentTradesGet200ResponseWithDefaults instantiates a new ParsedBookMarketSymbolRecentTradesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParsedBookMarketSymbolRecentTradesGet200ResponseWithDefaults() *ParsedBookMarketSymbolRecentTradesGet200Response {
	this := ParsedBookMarketSymbolRecentTradesGet200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *ParsedBookMarketSymbolRecentTradesGet200Response) GetResult() ParsedBookMarketSymbolRecentTradesGet200ResponseResult {
	if o == nil {
		var ret ParsedBookMarketSymbolRecentTradesGet200ResponseResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ParsedBookMarketSymbolRecentTradesGet200Response) GetResultOk() (*ParsedBookMarketSymbolRecentTradesGet200ResponseResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *ParsedBookMarketSymbolRecentTradesGet200Response) SetResult(v ParsedBookMarketSymbolRecentTradesGet200ResponseResult) {
	o.Result = v
}

func (o ParsedBookMarketSymbolRecentTradesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParsedBookMarketSymbolRecentTradesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *ParsedBookMarketSymbolRecentTradesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParsedBookMarketSymbolRecentTradesGet200Response := _ParsedBookMarketSymbolRecentTradesGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParsedBookMarketSymbolRecentTradesGet200Response)

	if err != nil {
		return err
	}

	*o = ParsedBookMarketSymbolRecentTradesGet200Response(varParsedBookMarketSymbolRecentTradesGet200Response)

	return err
}

type NullableParsedBookMarketSymbolRecentTradesGet200Response struct {
	value *ParsedBookMarketSymbolRecentTradesGet200Response
	isSet bool
}

func (v NullableParsedBookMarketSymbolRecentTradesGet200Response) Get() *ParsedBookMarketSymbolRecentTradesGet200Response {
	return v.value
}

func (v *NullableParsedBookMarketSymbolRecentTradesGet200Response) Set(val *ParsedBookMarketSymbolRecentTradesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableParsedBookMarketSymbolRecentTradesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableParsedBookMarketSymbolRecentTradesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParsedBookMarketSymbolRecentTradesGet200Response(val *ParsedBookMarketSymbolRecentTradesGet200Response) *NullableParsedBookMarketSymbolRecentTradesGet200Response {
	return &NullableParsedBookMarketSymbolRecentTradesGet200Response{value: val, isSet: true}
}

func (v NullableParsedBookMarketSymbolRecentTradesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParsedBookMarketSymbolRecentTradesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


