/*
 * Cube Iridium HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@cube.exchange
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersSubaccountsPostRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "accountType")]
    pub account_type: AccountType,
}

impl UsersSubaccountsPostRequest {
    pub fn new(name: String, account_type: AccountType) -> UsersSubaccountsPostRequest {
        UsersSubaccountsPostRequest {
            name,
            account_type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountType {
    #[serde(rename = "spot")]
    Spot,
    #[serde(rename = "margin")]
    Margin,
}

impl Default for AccountType {
    fn default() -> AccountType {
        Self::Spot
    }
}

