/*
 * Cube Iridium HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@cube.exchange
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersSubaccountSubaccountIdPatchRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl UsersSubaccountSubaccountIdPatchRequest {
    pub fn new(name: String) -> UsersSubaccountSubaccountIdPatchRequest {
        UsersSubaccountSubaccountIdPatchRequest {
            name,
        }
    }
}

