/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A collection of assets grouped by origination.  For `Crypto` assets, this is their native blockchain.  e.g `ETH` and `SHIB` are both on the `ethereum` (`CHAIN_ID = 0x1`) blockchain.
*/
export class MarketsGet200ResponseResultSourcesInner {
    /**
    * The Cube-assigned source ID.
    */
    'sourceId': number;
    /**
    * A human-readable name for this source.
    */
    'name': string;
    /**
    * The URL of a block explorer that can be used to view transactions.  The value is provided as a format string with a single `{}` placeholder for the transaction. e.g `https://etherscan.io/tx/{}`
    */
    'transactionExplorer'?: string | null;
    /**
    * The URL of a block explorer that can be used to view addresses.  The value is provided as a format string with a single `{}` placeholder for the address. e.g `https://etherscan.io/address/{}`
    */
    'addressExplorer'?: string | null;
    /**
    * Additional metadata about this source.
    */
    'metadata': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sourceId",
            "baseName": "sourceId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionExplorer",
            "baseName": "transactionExplorer",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressExplorer",
            "baseName": "addressExplorer",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MarketsGet200ResponseResultSourcesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

