/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MarketsGet200ResponseResultAssetsInner } from '../models/MarketsGet200ResponseResultAssetsInner';
import { MarketsGet200ResponseResultFeeTablesInner } from '../models/MarketsGet200ResponseResultFeeTablesInner';
import { MarketsGet200ResponseResultMarketsInner } from '../models/MarketsGet200ResponseResultMarketsInner';
import { MarketsGet200ResponseResultSourcesInner } from '../models/MarketsGet200ResponseResultSourcesInner';
import { HttpFile } from '../http/http';

export class MarketsGet200ResponseResult {
    'assets': Array<MarketsGet200ResponseResultAssetsInner>;
    'sources': Array<MarketsGet200ResponseResultSourcesInner>;
    'markets': Array<MarketsGet200ResponseResultMarketsInner>;
    'feeTables': Array<MarketsGet200ResponseResultFeeTablesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<MarketsGet200ResponseResultAssetsInner>",
            "format": ""
        },
        {
            "name": "sources",
            "baseName": "sources",
            "type": "Array<MarketsGet200ResponseResultSourcesInner>",
            "format": ""
        },
        {
            "name": "markets",
            "baseName": "markets",
            "type": "Array<MarketsGet200ResponseResultMarketsInner>",
            "format": ""
        },
        {
            "name": "feeTables",
            "baseName": "feeTables",
            "type": "Array<MarketsGet200ResponseResultFeeTablesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MarketsGet200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}

