/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A single row in a FeeTable.
*/
export class MarketsGet200ResponseResultFeeTablesInnerFeeTiersInner {
    /**
    * The order in which this tier is considered when applying the fee table that contains it.
    */
    'priority': number;
    /**
    * The multiplicative fee ratio for the resting order
    */
    'makerFeeRatio': number;
    /**
    * The multiplicative fee ratio for the aggressing order
    */
    'takerFeeRatio': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "makerFeeRatio",
            "baseName": "makerFeeRatio",
            "type": "number",
            "format": "double"
        },
        {
            "name": "takerFeeRatio",
            "baseName": "takerFeeRatio",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return MarketsGet200ResponseResultFeeTablesInnerFeeTiersInner.attributeTypeMap;
    }

    public constructor() {
    }
}

