/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MarketsGet200ResponseResultFeeTablesInnerFeeTiersInner } from '../models/MarketsGet200ResponseResultFeeTablesInnerFeeTiersInner';
import { HttpFile } from '../http/http';

/**
* A fee table consisting of one or more fee tiers. Each tier is applied in priority order and the first tier whose requirements match the characteristics of a given fill determines the fees for that fill. Each market is associated with a specific fee table via its \"feeTableId\".
*/
export class MarketsGet200ResponseResultFeeTablesInner {
    'feeTableId': number;
    'feeTiers': Array<MarketsGet200ResponseResultFeeTablesInnerFeeTiersInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "feeTableId",
            "baseName": "feeTableId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "feeTiers",
            "baseName": "feeTiers",
            "type": "Array<MarketsGet200ResponseResultFeeTablesInnerFeeTiersInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MarketsGet200ResponseResultFeeTablesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

