/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsersSubaccountSubaccountIdPositionsGet200ResponseResultValueInnerInner } from '../models/UsersSubaccountSubaccountIdPositionsGet200ResponseResultValueInnerInner';
import { HttpFile } from '../http/http';

export class UsersSubaccountSubaccountIdPositionsGet200ResponseResultValue {
    'name': string;
    'inner': Array<UsersSubaccountSubaccountIdPositionsGet200ResponseResultValueInnerInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "inner",
            "baseName": "inner",
            "type": "Array<UsersSubaccountSubaccountIdPositionsGet200ResponseResultValueInnerInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsersSubaccountSubaccountIdPositionsGet200ResponseResultValue.attributeTypeMap;
    }

    public constructor() {
    }
}

