/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsersInfoGet200ResponseResultApiKeysInner } from '../models/UsersInfoGet200ResponseResultApiKeysInner';
import { UsersInfoGet200ResponseResultGuardianHasKeyInner } from '../models/UsersInfoGet200ResponseResultGuardianHasKeyInner';
import { UsersInfoGet200ResponseResultKycStatusValue } from '../models/UsersInfoGet200ResponseResultKycStatusValue';
import { UsersInfoGet200ResponseResultRegistration } from '../models/UsersInfoGet200ResponseResultRegistration';
import { UsersInfoGet200ResponseResultSubaccountsInner } from '../models/UsersInfoGet200ResponseResultSubaccountsInner';
import { HttpFile } from '../http/http';

export class UsersInfoGet200ResponseResult {
    'apiKeys': Array<UsersInfoGet200ResponseResultApiKeysInner>;
    'subaccounts': Array<UsersInfoGet200ResponseResultSubaccountsInner>;
    'id': string;
    'email': string;
    'status': UsersInfoGet200ResponseResultStatusEnum;
    'vipLevel': number;
    'points': number;
    'mpcKeyId'?: number | null;
    'guardianHasKey'?: Array<UsersInfoGet200ResponseResultGuardianHasKeyInner> | null;
    'hasGuardianQuorum': boolean;
    'phoneNumber'?: string | null;
    'kycStatus': { [key: string]: UsersInfoGet200ResponseResultKycStatusValue; };
    'hasApprovedKyc': boolean;
    'registration'?: UsersInfoGet200ResponseResultRegistration | null;
    'firstName'?: string | null;
    'lastName'?: string | null;
    'country'?: string | null;
    'inviteId'?: string | null;
    'referralCode'?: string | null;
    'maxSubaccounts': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apiKeys",
            "baseName": "apiKeys",
            "type": "Array<UsersInfoGet200ResponseResultApiKeysInner>",
            "format": ""
        },
        {
            "name": "subaccounts",
            "baseName": "subaccounts",
            "type": "Array<UsersInfoGet200ResponseResultSubaccountsInner>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UsersInfoGet200ResponseResultStatusEnum",
            "format": ""
        },
        {
            "name": "vipLevel",
            "baseName": "vipLevel",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "mpcKeyId",
            "baseName": "mpcKeyId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "guardianHasKey",
            "baseName": "guardianHasKey",
            "type": "Array<UsersInfoGet200ResponseResultGuardianHasKeyInner>",
            "format": ""
        },
        {
            "name": "hasGuardianQuorum",
            "baseName": "hasGuardianQuorum",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "kycStatus",
            "baseName": "kycStatus",
            "type": "{ [key: string]: UsersInfoGet200ResponseResultKycStatusValue; }",
            "format": ""
        },
        {
            "name": "hasApprovedKyc",
            "baseName": "hasApprovedKyc",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "registration",
            "baseName": "registration",
            "type": "UsersInfoGet200ResponseResultRegistration",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "inviteId",
            "baseName": "inviteId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "referralCode",
            "baseName": "referralCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxSubaccounts",
            "baseName": "maxSubaccounts",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return UsersInfoGet200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UsersInfoGet200ResponseResultStatusEnum {
    Waitlist = 'waitlist',
    Active = 'active',
    Disabled = 'disabled'
}

