/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue } from '../models/UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue';
import { HttpFile } from '../http/http';

export class UsersSubaccountSubaccountIdWithdrawalsGet200Response {
    'result': { [key: string]: UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "{ [key: string]: UsersSubaccountSubaccountIdTransfersGet200ResponseResultWithdrawalsValue; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsersSubaccountSubaccountIdWithdrawalsGet200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

