/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Decimal } from '../models/Decimal';
import { HttpFile } from '../http/http';

export class UsersSubaccountSubaccountIdOrdersGet200ResponseResultOrdersInnerFillsInner {
    'tradeId': number;
    'baseBatchId'?: string | null;
    'quoteBatchId'?: string | null;
    'baseSettled': boolean;
    'quoteSettled': boolean;
    'baseAmount': Decimal;
    'quoteAmount': Decimal;
    'feeAmount': Decimal;
    'feeAssetId'?: number | null;
    'filledAt': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tradeId",
            "baseName": "tradeId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "baseBatchId",
            "baseName": "baseBatchId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "quoteBatchId",
            "baseName": "quoteBatchId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "baseSettled",
            "baseName": "baseSettled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "quoteSettled",
            "baseName": "quoteSettled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "baseAmount",
            "baseName": "baseAmount",
            "type": "Decimal",
            "format": "number"
        },
        {
            "name": "quoteAmount",
            "baseName": "quoteAmount",
            "type": "Decimal",
            "format": "number"
        },
        {
            "name": "feeAmount",
            "baseName": "feeAmount",
            "type": "Decimal",
            "format": "number"
        },
        {
            "name": "feeAssetId",
            "baseName": "feeAssetId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "filledAt",
            "baseName": "filledAt",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UsersSubaccountSubaccountIdOrdersGet200ResponseResultOrdersInnerFillsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

