/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Decimal } from '../models/Decimal';
import { HttpFile } from '../http/http';

export class UsersSubaccountSubaccountIdFillsGet200ResponseResultFillsInner {
    'marketId': number;
    'tradeId': number;
    'orderId': number;
    'side': UsersSubaccountSubaccountIdFillsGet200ResponseResultFillsInnerSideEnum;
    'aggressingSide'?: UsersSubaccountSubaccountIdFillsGet200ResponseResultFillsInnerAggressingSideEnum | null;
    'price'?: number | null;
    'quantity'?: number | null;
    'baseAmount': Decimal;
    'quoteAmount': Decimal;
    'feeAmount': Decimal;
    'feeAssetId'?: number | null;
    'filledAt': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "tradeId",
            "baseName": "tradeId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "UsersSubaccountSubaccountIdFillsGet200ResponseResultFillsInnerSideEnum",
            "format": ""
        },
        {
            "name": "aggressingSide",
            "baseName": "aggressingSide",
            "type": "UsersSubaccountSubaccountIdFillsGet200ResponseResultFillsInnerAggressingSideEnum",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "baseAmount",
            "baseName": "baseAmount",
            "type": "Decimal",
            "format": "number"
        },
        {
            "name": "quoteAmount",
            "baseName": "quoteAmount",
            "type": "Decimal",
            "format": "number"
        },
        {
            "name": "feeAmount",
            "baseName": "feeAmount",
            "type": "Decimal",
            "format": "number"
        },
        {
            "name": "feeAssetId",
            "baseName": "feeAssetId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "filledAt",
            "baseName": "filledAt",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UsersSubaccountSubaccountIdFillsGet200ResponseResultFillsInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UsersSubaccountSubaccountIdFillsGet200ResponseResultFillsInnerSideEnum {
    Bid = 'Bid',
    Ask = 'Ask'
}
export enum UsersSubaccountSubaccountIdFillsGet200ResponseResultFillsInnerAggressingSideEnum {
    Bid = 'Bid',
    Ask = 'Ask'
}

