/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UsersInfoGet200ResponseResultKycStatusValue {
    'level': number;
    'state': UsersInfoGet200ResponseResultKycStatusValueStateEnum;
    'approved': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "UsersInfoGet200ResponseResultKycStatusValueStateEnum",
            "format": ""
        },
        {
            "name": "approved",
            "baseName": "approved",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsersInfoGet200ResponseResultKycStatusValue.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UsersInfoGet200ResponseResultKycStatusValueStateEnum {
    Init = 'init',
    Pending = 'pending',
    Prechecked = 'prechecked',
    Queued = 'queued',
    OnHold = 'onHold',
    Completed = 'completed'
}

