/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UsersSubaccountsPostRequest {
    'name': string;
    'accountType': UsersSubaccountsPostRequestAccountTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountType",
            "baseName": "accountType",
            "type": "UsersSubaccountsPostRequestAccountTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsersSubaccountsPostRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UsersSubaccountsPostRequestAccountTypeEnum {
    Spot = 'spot',
    Margin = 'margin'
}

