/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsersSubaccountSubaccountIdOrdersGet200ResponseResultOrdersInner } from '../models/UsersSubaccountSubaccountIdOrdersGet200ResponseResultOrdersInner';
import { HttpFile } from '../http/http';

export class UsersSubaccountSubaccountIdOrdersGet200ResponseResult {
    'name': string;
    'orders': Array<UsersSubaccountSubaccountIdOrdersGet200ResponseResultOrdersInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<UsersSubaccountSubaccountIdOrdersGet200ResponseResultOrdersInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsersSubaccountSubaccountIdOrdersGet200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}

