/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UsersInfoGet200ResponseResultApiKeysInner {
    'isMasterKey': boolean;
    'subaccountIds': Array<number>;
    'accessLevel': UsersInfoGet200ResponseResultApiKeysInnerAccessLevelEnum;
    'apiKey': string;
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isMasterKey",
            "baseName": "isMasterKey",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subaccountIds",
            "baseName": "subaccountIds",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "accessLevel",
            "baseName": "accessLevel",
            "type": "UsersInfoGet200ResponseResultApiKeysInnerAccessLevelEnum",
            "format": ""
        },
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return UsersInfoGet200ResponseResultApiKeysInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UsersInfoGet200ResponseResultApiKeysInnerAccessLevelEnum {
    Read = 'read',
    Write = 'write'
}

