/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UsersInfoGet200ResponseResultGuardianHasKeyInner {
    'id': number;
    'name': string;
    'hasKey'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasKey",
            "baseName": "hasKey",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsersInfoGet200ResponseResultGuardianHasKeyInner.attributeTypeMap;
    }

    public constructor() {
    }
}

