/**
 * Cube Iridium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UsersAddressGet200ResponseResultAddressesInner {
    'id': string;
    'name': string;
    'sourceId': number;
    'assetId'?: number | null;
    'address': string;
    'status': UsersAddressGet200ResponseResultAddressesInnerStatusEnum;
    'createdAt': Date;
    'approvedAt': Date;
    'activeSince': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceId",
            "baseName": "sourceId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UsersAddressGet200ResponseResultAddressesInnerStatusEnum",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "approvedAt",
            "baseName": "approvedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "activeSince",
            "baseName": "activeSince",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return UsersAddressGet200ResponseResultAddressesInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UsersAddressGet200ResponseResultAddressesInnerStatusEnum {
    Pending = 'pending',
    Approved = 'approved',
    Active = 'active'
}

