/*
 * Cube Mendelev HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@cube.exchange
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParsedTickersGet200Response {
    #[serde(rename = "result")]
    pub result: Vec<models::ParsedTickersGet200ResponseResultInner>,
}

impl ParsedTickersGet200Response {
    pub fn new(result: Vec<models::ParsedTickersGet200ResponseResultInner>) -> ParsedTickersGet200Response {
        ParsedTickersGet200Response {
            result,
        }
    }
}

