/**
 * Cube Osmium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* New-order-reject indicates that a new-order request was not applied.
*/
export class OrderPost200ResponseResultOneOf1Rej {
    'msgSeqNum': number;
    /**
    * The client order ID specified in the new-order request.
    */
    'clientOrderId': number;
    /**
    * The request ID specified in the new-order request.
    */
    'requestId': number;
    /**
    * [Transact time](#transact-time)
    */
    'transactTime': number;
    'subaccountId': number;
    'reason': number;
    'marketId': number;
    'price'?: number | null;
    'quantity': number;
    'side': number;
    'timeInForce': number;
    'orderType': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "msgSeqNum",
            "baseName": "msgSeqNum",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "clientOrderId",
            "baseName": "clientOrderId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "transactTime",
            "baseName": "transactTime",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "subaccountId",
            "baseName": "subaccountId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "timeInForce",
            "baseName": "timeInForce",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "orderType",
            "baseName": "orderType",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return OrderPost200ResponseResultOneOf1Rej.attributeTypeMap;
    }

    public constructor() {
    }
}

