/**
 * Cube Osmium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderPatch200ResponseResultOneOf1Rej } from '../models/OrderPatch200ResponseResultOneOf1Rej';
import { HttpFile } from '../http/http';

export class OrderPatch200ResponseResultOneOf1 {
    'rej': OrderPatch200ResponseResultOneOf1Rej;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rej",
            "baseName": "Rej",
            "type": "OrderPatch200ResponseResultOneOf1Rej",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderPatch200ResponseResultOneOf1.attributeTypeMap;
    }

    public constructor() {
    }
}

