/**
 * Cube Osmium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* New-order-ack confirms a new-order request. The ack will be ordered before any fills for this order.
*/
export class OrderPost200ResponseResultOneOfAck {
    'msgSeqNum': number;
    /**
    * The client order ID specified in the new-order request.
    */
    'clientOrderId': number;
    /**
    * The request ID specified in the new-order request.
    */
    'requestId': number;
    /**
    * [Exchange order ID](#exchange-order-id)
    */
    'exchangeOrderId': number;
    'marketId': number;
    /**
    * If the order ultimately rests, the `price` field will include the resting price.
    */
    'price'?: number | null;
    /**
    * The quantity submitted in the new-order request.
    */
    'quantity': number;
    'side': number;
    'timeInForce': number;
    'orderType': number;
    /**
    * [Transact time](#transact-time)
    */
    'transactTime': number;
    'subaccountId': number;
    'cancelOnDisconnect': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "msgSeqNum",
            "baseName": "msgSeqNum",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "clientOrderId",
            "baseName": "clientOrderId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "exchangeOrderId",
            "baseName": "exchangeOrderId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "timeInForce",
            "baseName": "timeInForce",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "orderType",
            "baseName": "orderType",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "transactTime",
            "baseName": "transactTime",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "subaccountId",
            "baseName": "subaccountId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "cancelOnDisconnect",
            "baseName": "cancelOnDisconnect",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderPost200ResponseResultOneOfAck.attributeTypeMap;
    }

    public constructor() {
    }
}

