/**
 * Cube Osmium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Cancel all resting orders, optionally limiting to a particular market and / or order book side.
*/
export class OrdersDeleteRequest {
    /**
    * The subaccount to cancel orders for.
    */
    'subaccountId': number;
    /**
    * A request ID that is echoed back on the MassCancelAck and individual CancelOrderAck\'s.
    */
    'requestId': number;
    /**
    * If specified, only orders on the corresponding market will be canceled.
    */
    'marketId'?: number | null;
    /**
    * If specified, only orders with this side will be canceled.
    */
    'side'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subaccountId",
            "baseName": "subaccountId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "marketId",
            "baseName": "marketId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return OrdersDeleteRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

