/**
 * Cube Osmium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderPost200ResponseResultOneOf } from '../models/OrderPost200ResponseResultOneOf';
import { OrderPost200ResponseResultOneOf1 } from '../models/OrderPost200ResponseResultOneOf1';
import { OrderPost200ResponseResultOneOf1Rej } from '../models/OrderPost200ResponseResultOneOf1Rej';
import { OrderPost200ResponseResultOneOfAck } from '../models/OrderPost200ResponseResultOneOfAck';
import { HttpFile } from '../http/http';

export class OrderPost200ResponseResult {
    'ack': OrderPost200ResponseResultOneOfAck;
    'rej': OrderPost200ResponseResultOneOf1Rej;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ack",
            "baseName": "Ack",
            "type": "OrderPost200ResponseResultOneOfAck",
            "format": ""
        },
        {
            "name": "rej",
            "baseName": "Rej",
            "type": "OrderPost200ResponseResultOneOf1Rej",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderPost200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}

