/**
 * Cube Osmium HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@cube.exchange
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Decimal } from '../models/Decimal';
import { HttpFile } from '../http/http';

export class PositionsGet200ResponseResultInner {
    'assetId': number;
    'total': Decimal;
    'available': Decimal;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "number",
            "format": "uint64"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "Decimal",
            "format": "number"
        },
        {
            "name": "available",
            "baseName": "available",
            "type": "Decimal",
            "format": "number"
        }    ];

    static getAttributeTypeMap() {
        return PositionsGet200ResponseResultInner.attributeTypeMap;
    }

    public constructor() {
    }
}

