/*
 * Cube Osmium HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@cube.exchange
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrdersGet500Response {
    #[serde(rename = "error")]
    pub error: String,
}

impl OrdersGet500Response {
    pub fn new(error: String) -> OrdersGet500Response {
        OrdersGet500Response {
            error,
        }
    }
}

