/*
 * Cube Osmium HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@cube.exchange
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderDeleteRequest : Cancel a resting order. Note that this can be done before the order is acknowledged (an aggressive cancel) since the identifying field is the `client_order_id`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderDeleteRequest {
    #[serde(rename = "marketId")]
    pub market_id: i32,
    /// The order ID specified by the client on the NewOrder request.
    #[serde(rename = "clientOrderId")]
    pub client_order_id: i32,
    /// A request ID that is echoed back on the CancelOrderAck or CancelOrderReject
    #[serde(rename = "requestId")]
    pub request_id: i32,
    /// The subaccount that the NewOrder was placed on.
    #[serde(rename = "subaccountId")]
    pub subaccount_id: i32,
}

impl OrderDeleteRequest {
    /// Cancel a resting order. Note that this can be done before the order is acknowledged (an aggressive cancel) since the identifying field is the `client_order_id`.
    pub fn new(market_id: i32, client_order_id: i32, request_id: i32, subaccount_id: i32) -> OrderDeleteRequest {
        OrderDeleteRequest {
            market_id,
            client_order_id,
            request_id,
            subaccount_id,
        }
    }
}

